### PR TITLE
fixing get-status API endpoint

### PR DESCRIPTION
**Pull request by alastairong**

### CODE REVIEW

**Comment by alastairong** [comment]
Don't review this yet. I can't seem to untag reviewers...

**Comment by peeech** [comment]
Deal. It's still Draft, nobody will review this.

**Comment by alastairong** [comment]
@Holo-Host/central Ready for review.

**Comment by alastairong** [comment]
@peeech @filalex77 Need one of you to merge this in. Also, thoughts on whether I should have merge authorisation?

**Comment by filalex77** [comment]
> thoughts on whether I should have merge authorisation?

I'm 100% for this.

**Pull request merged**
