### PR TITLE
[QA TESTING] - Publisher Portal .1 and .2

### PR DESCRIPTION
**Pull request by zo-el**

### CODE REVIEW

**Comment by alastairong** [comment]
@zo-el if you're using this for testing reminder that:
1. You need to switch the match-server over if it's a new hash space
2. You need to include the code for #1273 as that is not yet in develop

**Comment by zo-el** [comment]
> @zo-el if you're using this for testing reminder that:
> 
>     1. You need to switch the match-server over if it's a new hash space
> 
>     2. You need to include the code for [Handle duplicate domains from HHA #1273](https://github.com/Holo-Host/holo-nixpkgs/pull/1273) as that is not yet in develop

We don't need the match server here, since we are using `devNet` again.

**Comment by alastairong** [comment]
Oh you're using devnet-resolver?

**Comment by zo-el** [comment]
This branch has just been updated to be used as a QA testing branch

**Pull request closed without merging**
