### PR TITLE
USB Holoport reset on master

### PR DESCRIPTION
**Pull request by peeech**
This PR is cherry picking commits from #440 and applies to master, therefore creates no merge conflicts. Read for testing.

### CODE REVIEW

**Comment by alastairong** [comment]
Is says this PR is to merge into develop?

**Comment by peeech** [comment]
ah lame me

**Comment by alastairong** [comment]
I don't think we should have the PR going straight to master, but I get that we need to figure out what to do without staging. let's discuss at OF tomorrow

**Comment by alastairong** [comment]
@peeech Have discussed with Mary and it's fine to merge to master after all testing is complete

**Comment by peeech** [comment]
I will only approve, convert to finished and merge this PR once I receive positive feedback from testers that their HoloPorts that follow #455 have passed QA @alastairong

**Comment by alastairong** [comment]
@peeech Thanks and agreed. This PR will only be merged post-QA.

**Pull request merged**
