### PR TITLE
modules/services/magic-wormhole-mailbox-server: add dynamic user 

### PR DESCRIPTION
**Pull request by samrose**

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
Have you tested that it's working after this change? I would recommend using downstream [`hpos-seed-roundtrip`](https://github.com/Holo-Host/hpos-seed/blob/6a2968f35658f1c1d842cc6870b61f6857c57a14/default.nix#L70) test to find out. Checkout `hpos-seed`, and change `nixpkgs.nix` so that it points to your local `holo-nixpkgs` instead of a fetch (something like `import ../holo-nixpkgs`). Then run `nix-build -A hpos-seed-roundtrip`.

**Comment by samrose** [comment]
> Have you tested that it's working after this change? I would recommend using downstream hpos-seed-roundtrip test to find out. Checkout hpos-seed, and change nixpkgs.nix so that it points to your local holo-nixpkgs instead of a fetch (something like import ../holo-nixpkgs). Then run nix-build -A hpos-seed-roundtrip.

Do you mean here on the same machine where I am testing out this service?

**Comment by yegortimoshenko** [comment]
I'm not sure I understand your question. `hpos-seed-roundtrip` is a NixOS test that launches a QEMU VM and checks (among other things) if `magic-wormhole-mailbox-server` works as expected.

**Comment by samrose** [comment]
(fwiw I should have created this PR as a draft. But I will just leave it here until complete)

**Comment by samrose** [comment]
For testing this, I set up a temporary machine (now gone) on an actual server, and converted to the wormhole-relay profile. The test actually did not work in that case. But I will investigate using `hpos-seed-roundtrip` to test 


The error when I deployed to temporary server was

```
systemctl status magic-wormhole-mailbox-server.service
● magic-wormhole-mailbox-server.service
   Loaded: loaded (/nix/store/rsfs7wn6i2g07v3p2ji690qkfaxq5fa6-unit-magic-wormhole-mailbox-server.service/magic-wormhole-mailbox-server.service; enabled; ven>
   Active: failed (Result: exit-code) since Mon 2020-02-24 18:42:11 UTC; 468ms ago
  Process: 11793 ExecStart=/nix/store/7slwginpk9bn7kifskyhd1ln6y4n18z5-python3-3.7.5-env/bin/twistd --nodaemon wormhole-mailbox (code=exited, status=1/FAILUR>
 Main PID: 11793 (code=exited, status=1/FAILURE)
       IP: 0B in, 0B out
      CPU: 2.139s

Feb 24 18:42:11 ewr1-t1.small.x86-01 twistd[11793]:   File "/nix/store/7slwginpk9bn7kifskyhd1ln6y4n18z5-python3-3.7.5-env/lib/python3.7/site-packages/wormhol>
Feb 24 18:42:11 ewr1-t1.small.x86-01 twistd[11793]:     dir=os.path.dirname(dbfile)
Feb 24 18:42:11 ewr1-t1.small.x86-01 twistd[11793]:   File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/tempfile.py", line 340, i>
Feb 24 18:42:11 ewr1-t1.small.x86-01 twistd[11793]:     return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
Feb 24 18:42:11 ewr1-t1.small.x86-01 twistd[11793]:   File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/tempfile.py", line 258, i>
Feb 24 18:42:11 ewr1-t1.small.x86-01 twistd[11793]:     fd = _os.open(file, flags, 0o600)
Feb 24 18:42:11 ewr1-t1.small.x86-01 twistd[11793]: OSError: [Errno 30] Read-only file system: 'relay.sqlite.1muuvp5r'
Feb 24 18:42:11 ewr1-t1.small.x86-01 systemd[1]: magic-wormhole-mailbox-server.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 18:42:11 ewr1-t1.small.x86-01 systemd[1]: magic-wormhole-mailbox-server.service: Failed with result 'exit-code'.
Feb 24 18:42:11 ewr1-t1.small.x86-01 systemd[1]: magic-wormhole-mailbox-server.service: Consumed 2.139s CPU time, no IP traffic.
```

I took this server down once I was done testing this out.

**Comment by samrose** [comment]
> I'm not sure I understand your question. `hpos-seed-roundtrip` is a NixOS test that launches a QEMU VM and checks (among other things) if `magic-wormhole-mailbox-server` works as expected.

I get it now, thanks for this great method to test this out with

**Comment by samrose** [comment]
[vm-test-run-hpos-seed-roundtrip.zip](https://github.com/Holo-Host/holo-nixpkgs/files/4251160/vm-test-run-hpos-seed-roundtrip.zip)

the test that passed locally with https://github.com/Holo-Host/holo-nixpkgs/commit/ece0867fceab709f615493ad6ad60d6cf5b053de

**Pull request merged**
