### PR TITLE
Remove Holochain-rust endpoints

### PR DESCRIPTION
**Pull request by alastairong**
@zo-el I think you added the service logger endpoints a while back. They're now obsolete right? And in any case, I imagine we would want Host Console UI to call service logger via the other HPOS-Holochain-API that Robbie wrote?

### CODE REVIEW

**Comment by zo-el** [comment]
> @zo-el I think you added the service logger endpoints a while back. They're now obsolete right? And in any case, I imagine we would want Host Console UI to call service logger via the other HPOS-Holochain-API that Robbie wrote?

Yes, that is obsolete. The new version of servicelogger does not include an endpoint that returns information that the `hpos-holochain-api` would need. This was excluded as a part of the MVP design of servicelogger.

**Review by zo-el — APPROVED** [review]
Looks good

**Comment by alastairong** [comment]
Note: Builds correctly on hydra. Failed check is because it is picking up an aborted build on hydra-2003

**Review by zippy — APPROVED** [review]

**Review by peeech — APPROVED** [review]
🥇

**Pull request merged**
