### PR TITLE
holochain-rust: bump to v0.0.42-alpha4

### PR DESCRIPTION
**Pull request by pjkundert**
DNAs and dependent packages updated to holochain-rust 0.0.41-alpha4, via their respective `release-0.0.41-alpha4-holo-nixpkgs` branches.

Run `nix-shell` and `hpos-shell`

### CODE REVIEW

**Comment by pjkundert** [comment]
This should be ready to go, but I'm having trouble running `hpos-shell` (running out of disk space).

**Comment by pjkundert** [comment]
Actually, I think I also need to reference the `release-0.0.41-alpha4-holo-nixpkgs` branch of `hp-admin-crypto`.  I didn't think I needed to, but it also needs to be upgraded to HC 0.0.41-alpha4 and also it needs to reference the updated hpos-config repo in its Cargo.tomls...

**Comment by pjkundert** [comment]
OK, updated hp-admin-crypto; should be ready to test `hpos-shell`, but I can't get it to build (runs out of space)...

**Comment by pjkundert** [comment]
Depends on the following dependency tags and dependent repo pulls:
- https://github.com/holochain/holochain-rust/releases/tag/v0.0.41-alpha4-holo-nixpkgs (tag, so referenced commit will persist)  Cannot be merged to master or develop, because it is incompatible with the `holonix` infrastructure.  Supports holo-nixpkgs builds.  Contains some fixes corresponding to commits that have subsequently been merged, and will be resolved when we merge in the next `release-0.0.42-alpha...` branch...

- https://github.com/Holo-Host/holo-hosting-app/pull/42
- https://github.com/Holo-Host/holofuel/pull/48
- https://github.com/Holo-Host/servicelogger/pull/14
- https://github.com/Holo-Host/holo-communities-dna/pull/6 (merged)
- https://github.com/Holo-Host/servicelogger/pull/14
- https://github.com/holochain/happ-store/pull/30
- https://github.com/Holo-Host/holo-router/pull/9
- https://github.com/Holo-Host/hpos-config/pull/41
- https://github.com/Holo-Host/hp-admin-crypto/pull/9

**Comment by yegortimoshenko** [comment]
Thanks for listing upstream PRs!

**Comment by yegortimoshenko** [comment]
Merge status:

- [ ] https://github.com/Holo-Host/holo-hosting-app/pull/42
- [ ] https://github.com/Holo-Host/holofuel/pull/48
- [ ] https://github.com/Holo-Host/servicelogger/pull/14
- [ ] https://github.com/Holo-Host/holo-communities-dna/pull/6
- [ ] https://github.com/Holo-Host/servicelogger/pull/14
- [ ] https://github.com/holochain/happ-store/pull/30
- [ ] https://github.com/Holo-Host/holo-router/pull/9
- [ ] https://github.com/Holo-Host/hpos-config/pull/41
- [ ] https://github.com/Holo-Host/hp-admin-crypto/pull/9

**Comment by yegortimoshenko** [comment]
@pjkundert: it would be better to not make `develop` merges, because I have to get rid of all of them before merging back into `develop` to keep sane Git history. I'll resolve conflicts, if any, during the rebase right before the merge.

**Comment by yegortimoshenko** [comment]
Also, make sure that there is one empty line between commit message and commit description. Otherwise commit description is read as part of commit message, and what I see e.g. during rebase is this:

```
pick 71dbf73 dna-packages: Update servicelogger to HC v0.0.41-alpha4 o Depends on updated holofuel and holo-hosting-app DNAs
```

**Comment by pjkundert** [comment]
Sorry about pulling in develop, it was to test.  I could force push it back if that helps.  We can’t revise though - the commits are referenced by several repos, and must be —no-ff merged so they remain...

**Comment by pjkundert** [comment]
Ya, I think we need to force this back to the Pre-rebase state — or fix all the other repos, too, to now reference this new commits, and then fix this to reference the new DNA commits, ...   not really practical, I think.

**Comment by pjkundert** [comment]
OK, why don't we call this one 0.0.42-alpha3, and merge in `release-0.0.41-alpha4-holo-nixpkgs-old` (my original branch), first?  Since a bunch of DNAs and other repos (hpos-config) already reference its commits, we can't really abandon them.

I don't really understand the argument against merging branches back into develop, that have had develop pulled into them.  This is standard practice and has been done in holo-nixpkgs in the past.  The complex intertwining of commit hashes between multiple repos is very difficult to manage cleanly; we literally cannot rebase any of the branches used to implement this complex multi-repo release-0.0.41-alpha4 update, I think.

These commits have already been referenced in commits merged into master/develop branches in multiple DNA repos, and holo-config, hp-admin-crypto, etc.  So, we basically must merge this branch into develop now, I think.  Or change history on this repos (rebase `develop`) to reference the ~equivalent commits in this new branch (the update to HC 0.0.41-alpha4 + rustc nightly update).   OR, we can tag this branch in holo-nixpkgs, so its commits don't disappear (as we've done in holochain-rust, with `v0.0.41-alpha4-holo-nixpkgs`.)

**Pull request merged**
