### PR TITLE
overlays/holo-nixpkgs/holo-envoy: Update envoy

### PR DESCRIPTION
**Pull request by timotree3**

### CODE REVIEW

**Review by alastairong — APPROVED** [review]
Straightforward bump to tip of develop. Approved

**Comment by timotree3** [comment]
Don't merge yet. Current develop actually has an issue so I'll need to update this PR once that's fixed

**Comment by timotree3** [comment]
Closing in favor of #790

**Comment by asaneh** [comment]
> _No description provided._

**Pull request closed without merging**
