### PR TITLE
Implement feature toggles for HP Admin as a simple MVP

### PR DESCRIPTION
**Pull request by filalex77**
Superseeds #529.

Removed (in comparison to #529):
- `nixos-rebuild.service`
- `systemd.paths.hpos-admin-features-rebuild` (see 70eca00)

### CODE REVIEW

**Review by filalex77 — COMMENTED** [review]
Self-review.

**Review by peeech — APPROVED** [review]

**Review by alastairong — APPROVED** [review]
Confirmed that this works on my holoport and meets acceptance criteria.

**Comment by filalex77** [comment]
Thanks @peeech @alastairong for the help. It's easy to get lost in all the moving parts :)

**Comment by alastairong** [comment]
@filalex77 @peeech I am rebasing to reimplement tests and revert all changes to /config endpoint.

/config endpoint is used for changing holoport name, so we don't want to break that

**Comment by alastairong** [comment]
Tests don't work so I re-disabled them. But still keeping the removal of the `/config` changes

**Pull request merged**
