### PR TITLE
Revert all DNAs to the ones using generic sim2h_url

### PR DESCRIPTION
**Pull request by peeech**
Test PR for checking if sim2h communication works between DNS once they all use same sim2h server.

### CODE REVIEW

**Comment by alastairong** [comment]
Do we still need to do this given the DNA upgrade issue?

**Comment by peeech** [comment]
I know that transactions go through with this regression. Do they work outside of it? Will see and keep you updated @alastairong

**Comment by alastairong** [comment]
Ok. I'll wait until tomorrow to switch over and reset

**Comment by alastairong** [comment]
@peeech Don't worry about testing if it works on the new DNA. At PO sync we agreed to just stick with public.sim2h because not having sim2h server specified in the DNA also makes final exam testing easier.

This also buys time for a better long term solution.

**Comment by peeech** [comment]
This implies that I am converting this PR to an actual PR that reverts DNA update, that way all the DNAs will use public.sim2h.net.

**Comment by peeech** [comment]
I'm too lazy to do it by hand :-)

**Pull request merged**
