### PR TITLE
Nixpkgs: automatically update the channel once a month

### PR DESCRIPTION
**Pull request by grahamc**
The current version of the pinned Nixpkgs is from December of last year. Pinning Nixpkgs is a great strategy for reproducibility and sharing consistent environments, but it is important to also update that pin on a regular basis. This PR implements that regular, automatic updating.

This PR introduces a script to automatically update the pinned version of Nixpkgs when it is run. It queries monitoring.nixos.org to identify the currently stable channel (nixos-21.05, nixos-21.11, etc.) and fetches that channel's current revision. This way you won't need to manually update the script when 22.05 comes out.

In a follow-up PR we'll add a GitHub Action to automatically, regularly send a PR updating the pin.

### CODE REVIEW

**Comment by alastairong** [comment]
@peeech Do we really want to automatically update nixpkgs regularly? What's the risk for us?

**Comment by peeech** [comment]
What we are talking about here is automatically created PR that updates pinned version of `nixpkgs`, not an automatic upgrade.
With such an aproach it is gonna be very easy to just run tests (e.g. nightly-test) on this PR and decide if we can merge or not. To be honest we've concluded that this is the best possible approach, because staying far behind official releases creates a lot of blockers for us during development of `holo-nixpkgs`.

**Review by peeech — APPROVED** [review]
Great.

When I ran `update-nixpkgs.sh` locally today I got
```
---> Latest stable Nixpkgs channel nixos-21.11 is at revision e34c5379866833f41e2a36f309912fa675d687c7
```

**Comment by peeech** [comment]
Merging this PR will effectively bump NixOs on all the Holoports to rev `a284564b7f75ac4db73607db02076e8da9d42c9d`. Before I actually merge this PR I have to run `nightly-tests` on holoports following it. @grahamc

**Comment by grahamc** [comment]
We just pushed an additional commit, it adds a GitHub Action which will on a monthly basis PR an update. You can see an example of this happening here: https://github.com/DeterminateSystems/holo-nixpkgs/pull/1

**Comment by peeech** [comment]
AFAIU from the code of [create-pull-request](https://github.com/peter-evans/create-pull-request) this will create a PR against default branch (which is in our case `develop`). Looks great.

**Comment by peeech** [comment]
Before merging our codebase will need some clean-up to remove syntax update warnings:
```
holo-nixpkgs-auto-upgrade-start[2718]: trace: Warning: `stdenv.lib` is deprecated and will be removed in the next release. Please use `lib` instead. For more information see https://github.com/NixOS/nixpkgs/issues/108938
holo-nixpkgs-auto-upgrade-start[2718]: trace: Warning: `stdenv.lib` is deprecated and will be removed in the next release. Please use `lib` instead. For more information see https://github.com/NixOS/nixpkgs/issues/108938
holo-nixpkgs-auto-upgrade-start[2718]: trace: warning: The option `services.mingetty' defined in `/nix/var/nix/profiles/per-user/root/channels/holo-nixpkgs/profiles/logical/hpos' has been renamed to `services.getty'.
```

**Pull request merged**
