### PR TITLE
matching-engine nix server

### PR DESCRIPTION
**Pull request by alastairong**
Profile, overlays, and services for a matching engine server

### CODE REVIEW

**Comment by alastairong** [comment]
Now that hydra can build private repos this is ready for review! Don't merge yet though.

**Review by Br1ght0ne — APPROVED** [review]
LGTM, read through most of the code.

**Comment by alastairong** [comment]
@peeech since hydra now builds private repos can we merge this?

**Review by peeech — APPROVED** [review]
Approved with comment about https and autoUpdate summarized in an issue #809 and #810

**Pull request merged**
