### PR TITLE
modules/dev-settings: init, use in profiles/development

### PR DESCRIPTION
**Pull request by filalex77**

### CODE REVIEW

**Comment by filalex77** [comment]
As we are going to use `profiles.*` options in `configuration.nix` after #497, I propose to:

- remove `cfg.settings`, leaving only `cfg.enable`
- make `dev-settings.toml` to always be just a selection of attributes from `configuration.nix` set
  - currently this is only `profiles`

Thus `modules/dev-settings` is only responsible for making feature toggles made in `configuration.nix` readable by software that doesn't speak Nix but can read TOML.

**Comment by peeech** [comment]
@alastairong can you organize a spike around it? I'd love to contribute but will have to download this piece of knowledge to my brain which is busy with some other stuff ATM.

**Comment by alastairong** [comment]
@filalex77 @peeech How urgent is this? I would really like us to make progress with the nano before we get back to developer profile related work.

**Comment by peeech** [comment]
This is a part of profiles work. So it would be healthier to finish this spike before mofving on to nanos

**Comment by alastairong** [comment]
The original reason to do the profiles work was for bump-dna to work, and nothing else. That was the specific pull. If we are now able to make bump DNA work then we really cannot afford to be spending more time on the profiles.

**Comment by filalex77** [comment]
Closing for now, reopening if further uses (besides `bump-dna`) emerge.

**Pull request closed without merging**
