### PR TITLE
update(profiles/logical/holo/hydra): update hydra pin to include new error message

### PR DESCRIPTION
**Pull request by firestack**
The Hydra PR (NixOS/hydra!1203) adding more details to error messages when the child worker process dies has been merged! 
This PR updates the hydra upstream pin to include the commit rev which contains these changes.

Closes https://github.com/Holo-Host/bugs-n-issues/issues/39

### CODE REVIEW

**Comment by firestack** [comment]
There's an evaluation error in `hpos-api-tests`.
```
in job ‘hpos-api-tests’:
error: creating file '/nix/store/add-2612102-0/x/pkgs/development/python-modules/twentemilieu/default.nix': No such file or directory```

**Comment by firestack** [comment]
I tried to reproduce but just got a successful test 😕 
```
nix-build ./release.nix -A holo-nixpkgs.src -o holo-nixpkgs
nix-build ./release.nix -A hpos-api-tests -I holo-nixpkgs=./holo-nixpkgs/
```

**Comment by firestack** [comment]
Evaluation error is gone after pushing an empty commit.

**Comment by peeech** [comment]
:yayyyeeee:

**Review by peeech — APPROVED** [review]

**Pull request merged**
