### PR TITLE
Bump pinned nixos to release-20.03

### PR DESCRIPTION
**Pull request by filalex77**
Next steps from this PR (taken from [Hydra evaluation errors]):

- [x] clear upgrade path for Hydra through `hydra-migration` package (outlined in [release notes for 20.03])
- [x] renaming option declarations for `services.dnscrypt-proxy2`, which was upstreamed
- [x] sorting out declarations for `security.acme.{acceptTerms,email}` in necessary places
- [ ] fixing outdated OpenSSL in Darwin build of `hpos-init`

[release notes for 20.03]: https://nixos.org/nixos/manual/release-notes.html#sec-release-20.03
[Hydra evaluation errors]: https://hydra.holo.host/jobset/holo-nixpkgs/453#tabs-errors

### CODE REVIEW

**Comment by alastairong** [comment]
@filalex77 What is the purpose of this bump and is there a meaningful risk that it breaks anything?

**Comment by filalex77** [comment]
@alastairong The primary reasons are improved testing support with Python, Hydra optimization, upstreaming of some Nix code in nixpkgs, and a lot of bugfixes.

---

Next steps from this PR (taken from [Hydra evaluation errors]):

- [ ] clear upgrade path for Hydra through `hydra-migration` package (outlined in [release notes for 20.03])
- [ ] renaming option declarations for `services.dnscrypt-proxy2`, which was upstreamed
- [ ] sorting out declarations for `security.acme.{acceptTerms,email}` in necessary places
- [ ] fixing outdated OpenSSL in Darwin build of `hpos-init`

[release notes for 20.03]: https://nixos.org/nixos/manual/release-notes.html#sec-release-20.03
[Hydra evaluation errors]: https://hydra.holo.host/jobset/holo-nixpkgs/453#tabs-errors

**Comment by alastairong** [comment]
@filalex77 @peeech Given that an OS change is far reaching, we will need to discuss how we properly test / QA this update

**Comment by mmahut** [comment]
The openssl is problamatic as a chicken-egg problem. Given openssl 1.0 has been marked as `InsecurePackages` in 20.03, it fails on a hydra agent building that is not running 20.03. We should update hydra before letting it build 20.03.

**Comment by mmahut** [comment]
Are we dropping this effort?

**Comment by filalex77** [comment]
@mmahut This PR was closed in order to allow current Hydra (19.09) to proceed with other evaluations, as it was taking a lot of time (and erroring in the end).
This needs more work, but it's a second priority after stabilizing current Hydra.
So no, the effort is still planned :)

**Pull request closed without merging**
